In [5]:
import pandas as pd
df = pd.read_csv('csv/AptitudeCommunication.csv')
df.head()

Name  Aptitude  Communication    Class
0  Karuna         2            5.0  Speaker
1  Bhavan         2            6.0  Speaker
2  Gaurav         7            6.0   Leader
3   Parul         7            2.5    Intel
4  Dinesh         8            6.0   Leader

In [6]:
df = df.drop('Name', axis=1)
df.head()

Aptitude  Communication    Class
0         2            5.0  Speaker
1         2            6.0  Speaker
2         7            6.0   Leader
3         7            2.5    Intel
4         8            6.0   Leader

In [7]:
x = df.drop('Class', axis=1)
y = df['Class']
print(x.shape, y.shape)

(14, 2) (14,)


In [8]:
from sklearn.neighbors import KNeighborsClassifier
nn = KNeighborsClassifier(n_neighbors=5)
model = nn.fit(x, y)
y_pred = model.predict(x)
y_pred

array(['Speaker', 'Speaker', 'Leader', 'Intel', 'Leader', 'Speaker',
       'Intel', 'Speaker', 'Intel', 'Leader', 'Intel', 'Leader', 'Intel',
       'Leader'], dtype=object)

In [9]:
dataframe = pd.DataFrame({'y':y, 'y_pred': y_pred})
dataframe

y   y_pred
0   Speaker  Speaker
1   Speaker  Speaker
2    Leader   Leader
3     Intel    Intel
4    Leader   Leader
5   Speaker  Speaker
6     Intel    Intel
7   Speaker  Speaker
8     Intel    Intel
9    Leader   Leader
10    Intel    Intel
11   Leader   Leader
12    Intel    Intel
13   Leader   Leader

In [27]:
model.predict([[10,4]])

array(['Leader'], dtype=object)

## Social_Network_Ads

In [36]:
df = pd.read_csv('csv/Social_Network_Ads.csv')
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [37]:
df = df.drop('User ID', axis=1)

In [38]:
df.head(2)

Gender  Age  EstimatedSalary  Purchased
0   Male   19            19000          0
1   Male   35            20000          0

In [39]:
import numpy as np
df['Gender'] = np.where(df["Gender"]=='Male', 1, 0)
df

Gender  Age  EstimatedSalary  Purchased
0         1   19            19000          0
1         1   35            20000          0
2         0   26            43000          0
3         0   27            57000          0
4         1   19            76000          0
..      ...  ...              ...        ...
395       0   46            41000          1
396       1   51            23000          1
397       0   50            20000          1
398       1   36            33000          0
399       0   49            36000          1

[400 rows x 4 columns]

In [40]:
y = df['Purchased']
x = df.drop('Purchased', axis=1)
print(x.shape, y.shape)

(400, 3) (400,)


In [46]:
from sklearn.neighbors import KNeighborsClassifier
nn = KNeighborsClassifier(n_neighbors = 20)
model = nn.fit(x,y)
y = model.predict([[1, 50, 41000]])
y

ValueError: Found input variables with inconsistent numbers of samples: [400, 1]

## Fish.csv

In [58]:
fish = pd.read_csv('csv/Fish.csv')
fish.head()

Species  Weight  Length1  Length2  Length3   Height   Width
0   Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1   Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2   Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3   Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4   Bream   430.0     26.5     29.0     34.0  12.4440  5.1340

In [59]:
x = fish.drop(columns = ['Species', 'Weight'], axis=1)
y = fish['Weight']
print(x.shape, y.shape)

(159, 5) (159,)


In [60]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state =42)
print(x_train.shape, x_test.shape, y_train.shape, y_test.shape)

(127, 5) (32, 5) (127,) (32,)


In [61]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
model = lr.fit(x_train, y_train)
y_pred = model.predict(x_test)
y_pred

array([  77.68563317, -159.12460639,  385.1673549 ,  300.26119445,
        179.41023158,  775.66726232, -214.43415538,  274.90963757,
        268.44510975, 1116.01153223,  610.12007978,  786.34393233,
        585.01831604,  172.12366335,  652.8595541 ,  785.41425179,
        926.40448191,  351.83433222,  256.32442006,  587.20219745,
       -175.74829352,  619.14709502,  516.45091187,  515.98797368,
        788.64695281,  909.00622172,  219.68134027,  305.35126984,
       -237.80116525, -178.93943304,  688.57820552,   23.23863135])

In [62]:
from sklearn import metrics
print('MAE : ', metrics.mean_absolute_error(y_test, y_pred))
print('MSE : ', metrics.mean_squared_error(y_test, y_pred))
print('R2 score : ', metrics.r2_score(y_test, y_pred))

MAE :  103.90941708422304
MSE :  16763.887193140756
R2 score :  0.8821430593048694


In [65]:
from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures(degree = 3)
x_poly = poly.fit_transform(x)
x_poly

array([[  1.        ,  23.2       ,  25.4       , ..., 533.495808  ,
        186.167808  ,  64.964808  ],
       [  1.        ,  24.        ,  26.3       , ..., 670.59892224,
        231.35662817,  79.81803672],
       [  1.        ,  23.9       ,  26.5       , ..., 719.48916561,
        272.97202012, 103.5647614 ],
       ...,
       [  1.        ,  12.1       ,  13.        , ...,   6.51098268,
          3.5909056 ,   1.98043885],
       [  1.        ,  13.2       ,  14.3       , ...,  17.06055993,
         12.27638175,   8.8337985 ],
       [  1.        ,  13.8       ,  15.        , ...,  16.15697982,
         10.3547495 ,   6.63619305]])

In [66]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x_poly,y, test_size = 0.2, random_state =42)
print(x_train.shape, x_test.shape, y_train.shape, y_test.shape)

(127, 56) (32, 56) (127,) (32,)


In [67]:
lr = LinearRegression()
model = lr.fit(x_train, y_train)
y_pred = model.predict(x_test)
y_pred

array([  93.31759262,   16.88979149,  167.61251068,  250.2587738 ,
        143.6597805 ,  682.56202507,   19.43542099,  185.44937897,
        180.52398872, 1358.12294006,  529.42295265,  834.33101463,
        571.40335846,  150.54441643,  704.70066452,  880.72776031,
        988.18909454,  233.97110558,  190.33507538,  588.2348175 ,
         47.12004662,  664.20123863,  640.11573792,  365.28347969,
        859.02360916, 1044.15058327,  156.21936035,  244.16114044,
        -20.47327805,   44.97657204,  456.85372734,   82.2109642 ])

In [68]:
from sklearn import metrics
print('MAE : ', metrics.mean_absolute_error(y_test, y_pred))
print('MSE : ', metrics.mean_squared_error(y_test, y_pred))
print('R2 score : ', metrics.r2_score(y_test, y_pred))

MAE :  54.59300298690796
MSE :  7284.553939417032
R2 score :  0.948786624979221
